# Generated by Django 2.2.2 on 2019-06-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DilemmaPartOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilemma_part_one', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DilemmaPartTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dilemma_part_two', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonPartTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('selected_option', models.CharField(max_length=50)),
                ('dilemma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reason_part_two', to='easydilemma.DilemmaPartTwo')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonPartOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('selected_option', models.CharField(max_length=50)),
                ('dilemma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reason_part_one', to='easydilemma.DilemmaPartOne')),
            ],
        ),
        migrations.CreateModel(
            name='Dilemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('dilemma_part_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easydilemma.DilemmaPartOne')),
                ('dilemma_part_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easydilemma.DilemmaPartTwo')),
            ],
        ),
    ]
