# Generated by Django 2.2.2 on 2019-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0002_dilemma_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dilemma',
            name='should_post',
            field=models.BooleanField(default=True),
        ),
    ]
