# Generated by Django 2.2.6 on 2019-10-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0003_dilemma_should_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='dilemma',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='dilemma',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='dilemma',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
