# Generated by Django 2.2.2 on 2019-06-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0003_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
