# Generated by Django 2.2.2 on 2019-06-14 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0004_delete_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasonpartone',
            name='dilemma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reason_part_one', to='easydilemma.DilemmaPartOne'),
        ),
        migrations.AlterField(
            model_name='reasonparttwo',
            name='dilemma',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reason_part_two', to='easydilemma.DilemmaPartTwo'),
        ),
    ]
