# Generated by Django 2.2.6 on 2019-10-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0005_dilemma_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dilemma',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
