# Generated by Django 2.2.6 on 2019-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0006_auto_20191020_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilemma',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
