# Generated by Django 2.2.2 on 2019-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0006_dilemma_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilemma',
            name='result',
            field=models.TextField(default='This is here before i set the result field'),
        ),
    ]
