# Generated by Django 2.2.2 on 2019-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easydilemma', '0007_auto_20190616_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilemma',
            name='result',
            field=models.TextField(),
        ),
    ]
